export const SET_PEOPLE_LIST = "SET_PEOPLE_LI'ST";
export const FETCH_PEOPLE_LIST_IN_PROGRESS = "FETCH_PEOPLE_LIST_IN_PROGRESS";
export const SET_PLANET_INFO = "SET_PLANET_INFO";

export const TOGGLE_PLANET_INFO = "TOGGLE_PLANET_INFO";